"""baseline — create all platform-base tables

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-03

Baseline migration: creates every platform-base table from the ORM metadata
(roles, users, api_keys, audit_log, channel_configs, device_tokens, notifications,
branding, report_jobs). Scenarios add their own tables in later autogenerated
migrations (target_metadata is wired, so `alembic revision --autogenerate` works).
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def _metadata():
    # Import inside the function so the models register on Base.metadata at run time.
    from edge.db.base import Base
    import edge.auth.models  # noqa: F401
    import edge.core.audit  # noqa: F401
    import edge.messaging  # noqa: F401
    import edge.branding.models  # noqa: F401
    import edge.reports.models  # noqa: F401

    return Base.metadata


def upgrade() -> None:
    _metadata().create_all(op.get_bind())


def downgrade() -> None:
    _metadata().drop_all(op.get_bind())
